### PR TITLE
Fix a retain cycle in the object notifier

### LINKED ISSUE #340: "Too many open files" exceptions when running tests on master
```
realm-object-store$ git show-ref HEAD
9ac9626f65c27306755e9cf61bd803d63a77263c refs/remotes/origin/HEAD
realm-object-store$ ulimit -n
256
realm-object-store$ ./tests/tests 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests is a Catch v1.3.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
notifications: async delivery
  notifications for remote changes
-------------------------------------------------------------------------------
realm-object-store/tests/results.cpp:55
...............................................................................

realm-object-store/tests/results.cpp:218: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Too many open files
```

`lsof` shows that most of the open files are Realm files (and their various locks). By adding some extra logging I determined that most of the Realm files opened by the [new tests in object.cpp](https://github.com/realm/realm-object-store/blob/0dc71fbfaf5e7361f0a06cd0db94767e6a4c5aa6/tests/object.cpp#L37-L159) are never being closed. From looking at the reference count on `r` as it goes out of scope it is apparent that there is a second reference to the Realm. A breakpoint added to `realm::_impl::ObjectNotifier::~ObjectNotifier()` is never hit, suggesting that this issue is similar in nature to a problem we had with collection notifications when they were first added, which was fixed in #77.

@tgoyne, can you please take a look?

### PR DESCRIPTION
**Pull request by tgoyne**
`unregister()` was never actually being called, so object notifiers would never get destroyed.

Add an assertion to the beginning of some of the test cases that there are no realms already open to catch this sort of thing before we hit the max file open limit.

Fixes #340.

### CODE REVIEW

File: src/impl/realm_coordinator.cpp [hunk 1]
```diff
@@ -302,6 +302,14 @@ void RealmCoordinator::clear_all_caches()
     }
 }
 
+void RealmCoordinator::assert_no_open_realms() noexcept
+{
+#ifdef REALM_DEBUG
```
Comment (bdash) [inline src/impl/realm_coordinator.cpp]: Why `REALM_DEBUG`? `REALM_ASSERTIONS_ENABLED` would be my inclination.
