### PR TITLE
Fix a crash when calling SyncManager::reset_for_testing

### LINKED ISSUE #269: `SyncSession` might be killed in the middle of the wait-for-upload callback
It's possible that `SyncSession` might be killed in the middle of its "wait for upload" callback if `SyncManager::reset_for_testing()` is called. If this is an issue, we should fix it.

### PR DESCRIPTION
**Pull request by bdash**
`SyncClient`'s lifetime was managed by a `shared_ptr`, resulting in `SyncManager::reset_for_testing` failing to destroy it when expected. This meant that its runloop was still running, and that it could continue to deliver callbacks to sessions that `reset_for_testing` was in the process of destroying.

To address this `SyncClient` is now owned by `SyncManager`, with `SyncSession`'s holding only a reference to their client. This is safe because sync asserts that all sessions have been destroyed when the client is destroyed.

/cc @austinzheng @alazier 

Fixes #269.

### CODE REVIEW

File: src/sync/sync_session.cpp [hunk 1]
```diff
@@ -211,15 +211,7 @@ struct sync_session_states::Dying : public SyncSession::State {
     void enter_state(std::unique_lock<std::mutex>&, SyncSession& session) const override
     {
         size_t current_death_count = ++session.m_death_count;
-        session.m_session->async_wait_for_upload_completion([session=&session, current_death_count](std::error_code error_code) {
-            if (error_code == util::error::operation_aborted) {
```
Comment (austinzheng) [inline src/sync/sync_session.cpp]: Should we keep this? Are there any non-test situations in which the `Client` might be killed but the application continues running?

Comment (bdash) [inline src/sync/sync_session.cpp]: If we leave this early-return in place then sessions whose wait is aborted won't be removed from the inactive sessions list.

Comment (austinzheng) [inline src/sync/sync_session.cpp]: For example, in the case where the Client is stopped but the sessions were in the inactive sessions list? Okay, that makes sense.

**Comment by alazier** [comment]
This fixes the remaining issues we are seeing on JS
